[package]
name = "simple_parser_rs"
version = "0.1.0"
authors = ["Abdelhak Bougouffa <abougouffa@fedoraproject.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.4.2"